# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Use secrets
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
        run: |
          echo "VITE_API_KEY is: $VITE_API_KEY"
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build --platform linux/amd64 -t 99999944/daofa-web-admin .
      - name: Publish image to docker hub
        run: docker push 99999944/daofa-web-admin:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker container
        run: sudo docker pull 99999944/daofa-web-admin:latest
      - name: Delete old container
        run: sudo docker rm -f web-container
      - name: Run docker container
        run: sudo docker run --platform=linux/amd64 -d -p 3005:3000 --name web-container 99999944/daofa-web-admin:latest
